export const services = [
  {
    id: "outsourcing",
    title: "Specialized Outsourcing",
    subtitle: "Top-tier remote engineering talent",
    description: "Deploy embedded engineering teams of senior developers and systems architects. We manage the screening, onboarding, and operational lifecycle to scale your technical capacity.",
    metrics: "+500 Engineers Vetted",
    features: ["Standardized Screening", "Embedded Agile Placement", "Lead Architect Supervision", "Transparent Service Agreements"],
    icon: "Users",
  },
  {
    id: "skill-hiring",
    title: "Specialized Skill Hiring",
    subtitle: "Fractional experts on-demand",
    description: "Engage fractional machine learning leads, security auditors, and system architects for project-specific timelines, mitigating long-term overhead.",
    metrics: "5–50 Day Engagements",
    features: ["Deep domain expertise", "Focused audit preparation", "Architecture reviews", "Immediate technical onboarding"],
    icon: "Briefcase",
  },
  {
    id: "ai-solutions",
    title: "AI Solutions & Automation",
    subtitle: "Custom LLM pipelines & workflows",
    description: "Design and implement custom RAG systems, agentic workflows, and automated pipelines engineered to reduce operational overhead.",
    metrics: "2–6 Week MVP Deployment",
    features: ["Custom RAG pipelines", "Agentic orchestration", "Fine-tuning pipelines", "Production deployments"],
    icon: "BrainCircuit",
  },
  {
    id: "data-annotations",
    title: "Data Annotation & Labeling",
    subtitle: "High-quality, at-scale training data",
    description: "High-precision labeling including semantic segmentation, named entity recognition (NER), and multi-stage QA validation for production-grade models.",
    metrics: "10M+ Annotations Delivered",
    features: ["Multi-stage validation", "Custom annotation tools", "Rigorous QA checks", "Secure data handling"],
    icon: "Layers",
  },
];
